receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

extensions:
  health_check:

exporters:
  logging:
    verbosity: detailed
  awsxray:
    region: eu-south-1
  awsemf:
    region: eu-south-1

service:
  extensions: [health_check]
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers:
        - otlp
      exporters:
        - logging
        - awsxray
    metrics:
      receivers:
        - otlp
      exporters:
        - logging
        - awsemf